#OPERATION KITTEN EXPLOSION

#TALK ABOUT OBJECT RELATIONAL MAPPING (ORM)

#REQUIRE GEMS-> PREWRITTEN RUBY (Ex. rspec)
require 'sqlite3'
require 'faker'

#CREATE SQLITE3 DATABASE
#sqlite3 database_name.db
db = SQLite3::Database.new("kittens.db")

#LEARN ABOUT FANCY STRING DELIMITERS

#CREATE A KITTENS TABLE

#ADD A TEST KITTEN

#EXPLORE ORM BY RETRIEVING DATA

#ADD KITTENS
